### ISSUE TITLE
Update auth api calls to return dynamic nav

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#58]
update auth api calls (login, passwordReset and signup) to now return:

```
AuthResponse:
      type: object
      properties:
        sessionID:
          type: string
        nav:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              icon:
                type: string
                description: base64 image string
              apiURL:
                type: string
              screenType:
                type: string
                enum:
                  - list
                  - detail
                  - profile
                  - findDoctor
```

For role type patient here's the nav for now:
```
{"nav": [
    {
        "title": "All",
        "icon": "<to be determined with Tony>",
        "apiURL": "baseDomainURL + /getPatientHomeItems",
        "screenType": "list"
    },
    {
        "title": "Payments",
        "icon": "<to be determined with Tony>",
        "apiURL": "baseDomainURL + /getPayments",
        "screenType": "list"
    },
    {
        "title": "Profile",
        "icon": "<to be determined with Tony>",
        "apiURL": "baseDomainURL + /getProfile",
        "screenType": "profile"
    }
]}
```

For role type doctor here's the nav for now:
```
{"nav": [
    {
        "title": "All",
        "icon": "<to be determined with Tony>",
        "apiURL": "baseDomainURL + /getDoctorHomeItems",
        "screenType": "list"
    },
    {
        "title": "Payments",
        "icon": "<to be determined with Tony>",
        "apiURL": "baseDomainURL + /getPayments",
        "screenType": "list"
    },
    {
        "title": "Profile",
        "icon": "<to be determined with Tony>",
        "apiURL": "baseDomainURL + /getProfile",
        "screenType": "profile"
    }
]}
```
Once we work on find a doctor then we'll add that to this nav as well

icons list:
https://docs.flutter.io/flutter/material/Icons-class.html
